env: "local"

access_ttl: 15m
refresh_ttl: 168h

http:
  port: ":8080"

secret: "mysecretword"

smtp:
  host: "smtp.gmail.com"
  port: 587
  user: "kirikl228666@gmail.com"
  password: "ufug owot exis ohst"
  from: "Auth Service <kirikl228666@gmail.com>"

redis_addr: "jwt-auth-redis:6379"

postgres:
  host: "jwt-auth-db"
  port: 5432
  user: postgres
  password: 123456
  dbname: jwt_db
  sslmode: disable