env: "local"

access_ttl: 15m
refresh_ttl: 168h

http:
  port: ":8080"

secret: "mysecretword"

smtp:
  host: 
  port: 
  user: 
  password: 
  from: 

redis_addr: "jwt-auth-redis:6379"

postgres:
  host: "jwt-auth-db"
  port: 5432
  user: 
  password: 
  dbname: jwt_db
  sslmode: disable
